# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: 
  create:
    tags:
      - .*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ecr:
    name: build and deploy image to AWS ECR
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIAUNDMPL7E7KYQ4SJD
          aws-secret-access-key: 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
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set Tag Number
        id: tag-number
        run: echo ::set-output name=tag::1
        
      - name: Check Tag Release
        env:
          RELEASE_VERSION: ${{ steps.tag-number.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: 303022694345.dkr.ecr.ap-northeast-2.amazonaws.com/asana-clone1
          ECR_REPOSITORY: demo
          IMAGE_TAG: ${{ steps.tag-number.outputs.tag }}
        run: |
          docker build -t demo .
          docker tag demo:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
